### ISSUE TITLE
Coverage failure with expected exceptions

### ISSUE THREAD

**Issue by Martin-Spamer** [jacoco/eclemma#133]
Unit Test with an expected exception are shown as not covered when running them through the debugger or adding logging proved the code is actually covered.

### Steps to reproduce

```
import static org.junit.Assert.fail;
import org.junit.Test;
public class CoverageFailure {
    @Test(expected = AssertionError.class)
    public void test() {
        fail("Coverage failure");
    }
}

```
**EclEmma version:**
EclEmma 2.3.1.201405111647
**Eclipse version**:
Eclipse Java EE IDE for Web Developers.
Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200

### Expected behaviour
All Code should be reported as covered by test.

### Actual behaviour
The example could is reported as not-covered by test.

**Comment by Godin** [comment]
@Martin-Spamer could you please try latest EclEmma release that is 2.3.3 ?

**Comment by Godin** [comment]
@Martin-Spamer more specifically: in EclEmma 2.3.3 this has been improved by upgrade to JaCoCo 0.7.6, so that it includes jacoco/jacoco#310. While it can be seen as imperfect as in your example, things got better - you can observe this on screenshots in mentioned PR or by updating your example to
```
public void test() {
  System.out.println("something");
  fail("Coverage failure");
}
```
where first line will be marked as covered.

This imperfection is also mentioned in [JaCoCo FAQ](http://www.eclemma.org/jacoco/trunk/doc/faq.html):
> ### Source code lines with exceptions show no coverage. Why?
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

**Comment by marchof** [comment]
Nothing we can do here at the EclEmma project. This is a documented limitation of JaCoCo, the library behind EclEmma.
