### ISSUE TITLE
Missed Coverage when Called Method Throws an Exception

### ISSUE THREAD

**Issue by numeralnathan** [jacoco/eclemma#61]
See the class FruitSalad.  The code coverage reports 100% for yuck() but 0% for mix().  If the throw statement in mix() is uncommented, then mix() achieves 100% code coverage.

public class FruitSalad
{
   public static void mix()
   {
      //throw new IllegalArgumentException();
      yuck();
   }

   public static void yuck()
   {
      throw new IllegalArgumentException();
   }
}

public class TestFruitSalad
{
   @SuppressWarnings("static-method")
   @Test(expected = IllegalArgumentException.class)
   public void mixItUp()
   {
      FruitSalad.mix();
   }
}

**Comment by C-Otto** [comment]
@nathanila I agree, please have a look at the JaCoCo mailing list and pull request https://github.com/jacoco/jacoco/pull/261

**Comment by nuwanw** [comment]
This issue is still in the latest release jacoco 0.7.8. Still it failed to count the line coverage when a method throws an exception. Will this be fixed in future release?

**Comment by C-Otto** [comment]
@nuwanw this issue is closed, and the release notes state that the feature was added to 0.7.5. Could you file a new issue here with detailled information?

**Comment by Godin** [comment]
@nuwanw @C-Otto there was an improvement for the case of exceptions (#310), however it has some limitations - see https://github.com/jacoco/jacoco/issues/370#issuecomment-267854179

If you have questions, then please use our mailing list to ask them - https://groups.google.com/forum/?fromgroups=#!forum/jacoco
instead of commenting in old closed tickets.
Thank you for your understanding!
